# Generated by Django 2.1.2 on 2018-10-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(default='', max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_rented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('rut', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Owner'),
        ),
    ]
